#
# clang-tidy-config.yaml
#

Checks: [
  'boost-*',
  'concurrency-*',
  'cppcoreguidelines-*',
  'google-*',
  'misc-*',
  'modernize-*',
  'performance-*',
  'portability-*',
  'readability-*',
  '-cppcoreguidelines-avoid-magic-numbers',
  '-cppcoreguidelines-avoid-non-const-global-variables',
  '-cppcoreguidelines-macro-usage',
  '-cppcoreguidelines-non-private-member-variables-in-classes',
  '-cppcoreguidelines-pro-bounds-constant-array-index',
  '-cppcoreguidelines-pro-bounds-pointer-arithmetic',
  '-cppcoreguidelines-pro-type-const-cast',
  '-cppcoreguidelines-pro-type-reinterpret-cast',
  '-cppcoreguidelines-pro-type-union-access',
  '-cppcoreguidelines-special-member-functions',
  '-google-build-using-namespace',
  '-google-runtime-int',
  '-misc-include-cleaner',
  '-misc-non-private-member-variables-in-classes',
  '-modernize-use-trailing-return-type',
  '-readability-identifier-length',
  '-readability-isolate-declaration',
  '-readability-magic-numbers',
]
HeaderFilterRegex: '.*'

# EOF
